name: 'Check Upmerge'
on:
  schedule:
    # Runs "At 18:00 every day" (see https://crontab.guru)
    - cron: '0 18 * * *'

permissions:
  contents: write
  pull-requests: write
  actions: read
  checks: write

jobs:
  check-upmerge:
    uses: collaborationFactory/github-actions/.github/workflows/fe-check-upmerge.yml@release/26.1
    secrets:
      SLACK_TOKEN_UPMERGE: ${{ secrets.SLACK_TOKEN_UPMERGE }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER: ${{ secrets.GIT_USER }}
