name: 'Cleanup Snapshots Action'
on:
  schedule:
    # Runs "At 00:00 on day-of-month 28 in every 3rd month." (see https://crontab.guru)
    - cron: '0 0 28 */3 *'

jobs:
  cleanup-snapshots:
    uses: collaborationFactory/github-actions/.github/workflows/fe-cleanup-snapshots.yml@release/23.3
    secrets:
      JFROG_BASE64_TOKEN: ${{ secrets.JFROG_BASE64_TOKEN }}
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_USER: ${{ secrets.JFROG_USER }}
      DOT_NPMRC: ${{ secrets.DOT_NPMRC }}
