name: 'Check Upmerge'
on:
  schedule:
    # Runs "At 18:00 every day" (see https://crontab.guru)
    - cron: '0 18 * * *'

permissions: write-all

jobs:
  check-upmerge:
    uses: collaborationFactory/github-actions/.github/workflows/fe-check-upmerge.yml@master

