name: 'Frontend Pull Request Snapshot CI'
on:
  pull_request:
    types: [labeled, synchronize, reopened]
    branches:
      - '**'

permissions:
  contents: write
  pull-requests: write
  actions: read
  checks: write

jobs:
  publish-pr-snapshot:
    uses: collaborationFactory/github-actions/.github/workflows/fe-pr-snapshot.yml@release/26.1
    with:
      GHA_BASE: ${{ github.event.pull_request.base.ref }}
    secrets:
      JFROG_BASE64_TOKEN: ${{ secrets.JFROG_BASE64_TOKEN }}
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_USER: ${{ secrets.JFROG_USER }}
      DOT_NPMRC: ${{ secrets.DOT_NPMRC }}
