name: 'Frontend Pull Request CI Template'
on:
  pull_request:
    branches:
      - '**'

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  install-deps:
    uses: collaborationFactory/github-actions/.github/workflows/fe-install-deps.yml@feature/PFM-ISSUE-10870-Share-CI-CD-workflows
    secrets:
      DOT_NPMRC: ${{ secrets.DOT_NPMRC }}

  build:
    uses: collaborationFactory/github-actions/.github/workflows/fe-build.yml@feature/PFM-ISSUE-10870-Share-CI-CD-workflows

  code-quality:
    uses: collaborationFactory/github-actions/.github/workflows/fe-code-quality.yml@feature/PFM-ISSUE-10870-Share-CI-CD-workflows

  e2e:
    uses: collaborationFactory/github-actions/.github/workflows/fe-e2e.yml@feature/PFM-ISSUE-10870-Share-CI-CD-workflows
    secrets:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
