name: 'Frontend Pull Request CI'
on:
  pull_request:
    branches:
      - '**'

permissions: write-all

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  install-deps:
    uses: collaborationFactory/github-actions/.github/workflows/fe-install-deps.yml@feature/PFM-ISSUE-26057-Allow-private-registry-in-Github-Actions-
    with:
      GHA_REF: ${{ github.event.pull_request.head.ref }}
    secrets:
      DOT_NPMRC: ${{ secrets.DOT_NPMRC }}

  build:
    needs: install-deps
    uses: collaborationFactory/github-actions/.github/workflows/fe-build.yml@feature/PFM-ISSUE-26057-Allow-private-registry-in-Github-Actions-
    with:
      GHA_REF: ${{ github.event.pull_request.head.ref }}
      GHA_BASE: ${{ github.event.pull_request.base.ref }}

  code-quality:
    needs: install-deps
    uses: collaborationFactory/github-actions/.github/workflows/fe-code-quality.yml@feature/PFM-ISSUE-26057-Allow-private-registry-in-Github-Actions-

  e2e:
    needs: install-deps
    uses: collaborationFactory/github-actions/.github/workflows/fe-e2e.yml@feature/PFM-ISSUE-26057-Allow-private-registry-in-Github-Actions-
    with:
      GHA_REF: ${{ github.event.pull_request.head.ref }}
      GHA_BASE: ${{ github.event.pull_request.base.ref }}
    secrets:
      # PERCY_TOKEN is optional, and it should only be provided in case you want to use Cypress with Percy
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
