name: 'Frontend Pull Request Close CI'
on:
  pull_request:
    types: [closed]
    branches:
      - '**'

permissions: write-all

jobs:
  remove-artifacts:
    uses: collaborationFactory/github-actions/.github/workflows/fe-pr-close.yml@improvement/PFM-ISSUE-13081-Investigate-if-we-can-use-nx-caching-only-for
    with:
      GHA_BASE: ${{ github.event.pull_request.base.ref }}
    secrets:
      JFROG_BASE64_TOKEN: ${{ secrets.JFROG_BASE64_TOKEN }}
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_USER: ${{ secrets.JFROG_USER }}
      DOT_NPMRC: ${{ secrets.DOT_NPMRC }}
