name: 'Frontend Tag Pushed CI'
on:
  push:
    tags:
      - '*/*'

permissions: write-all

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  release-version:
    uses: collaborationFactory/github-actions/.github/workflows/fe-release.yml@test-pp
    secrets:
      JFROG_BASE64_TOKEN: ${{ secrets.JFROG_BASE64_TOKEN }}
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_USER: ${{ secrets.JFROG_USER }}
      DOT_NPMRC: ${{ secrets.DOT_NPMRC }}
