name: 'collaboration Factory toolset'
description: 'Github Action our collaboration Factory repositories'
author: 'collaboration Factory AG'
branding:
  icon: 'command'
  color: 'blue'
inputs:
  s3_bucket:
    description: 's3 bucket containing the helm registry'
    required: true
  repo:
    description: 'Name of the helm registry'
    required: true
  aws_region:
    description: 'AWS region'
    required: false
    default: 'eu-west-1'
  aws_access_key_id:
    description: 'AWS IAM access key id'
    required: true
  aws_secret_access_key:
    description: 'AWS IAM secret access key'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "-e \"REPO=${{ inputs.repo }}\""
    - "-e \"S3_BUCKET=${{ inputs.s3_bucket }}\""
    - "-e \"AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }}\""
    - "-e \"AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }}\""
    - "-e \"AWS_DEFAULT_REGION=${{ inputs.aws_region }}\""
