name: 'Nx Run Many Action'
description: 'Github Action to run Nx command for many Nx projects'
inputs:
  target:
    description: 'Nx command'
    required: true
  jobIndex:
    description: 'Matrix job index'
    required: true
  jobCount:
    description: 'Matrix job count'
    required: true
  base:
    description: 'Base branch'
    required: true
runs:
  using: 'composite'
  steps:
    - run: echo $(pwd)
      shell: bash
    - run: echo "$GITHUB_ACTION_PATH/../../../fe-actions/scripts"
      shell: bash
    - run: ls -ll "$GITHUB_ACTION_PATH/../../../fe-actions/scripts"
      shell: bash
