name: 'Frontend Nx Run Many Action'
description: 'Github Action to run Nx command for many Nx projects'
inputs:
  target:
    description: 'Nx command'
    required: true
  jobIndex:
    description: 'Matrix job index'
    required: true
  jobCount:
    description: 'Matrix job count'
    required: true
  base:
    description: 'Base branch'
    required: true
  ref:
    description: 'Reference'
    required: true
runs:
  using: 'composite'
  steps:
    - run: cd "$GITHUB_ACTION_PATH/../../.." && pwd && npm ci
      shell: bash
    - run: npx ts-node "$GITHUB_ACTION_PATH/../../../tools/scripts/run-many/run-many.ts" ${{ inputs.target }} ${{ inputs.jobIndex }} ${{ inputs.jobCount }} ${{ inputs.base }} ${{ inputs.ref }}
      shell: bash
