name: Frontend Package Update

on:
  repository_dispatch:
    types: [frontend-packages-published]

jobs:
  update-packages:
    name: Update Frontend Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
        

      - name: Update packages
        uses: collaborationFactory/github-actions/.github/actions/backend-package-updater@master
        with:
          branch: ${{ github.event.client_payload.branch }}
          actor: ${{ github.event.client_payload.actor }}
          dot-npmrc: ${{ secrets.DOT_NPMRC }}
