name: 'Cleanup Snapshots Action'
description: 'Github Action to cleanup snapshots'
runs:
  using: 'composite'
  steps:
    - run: printenv
      shell: bash
    - run: cd "$GITHUB_ACTION_PATH/../../.." && pwd && npm ci
      shell: bash
    - run: npx ts-node "$GITHUB_ACTION_PATH/../../../tools/scripts/artifacts/main-snapshots.ts"
      shell: bash
