name: Cleanup Snapshot Artifacts on a CRON Schedule

on:
  schedule:
    # Runs "At 00:00 on day-of-month 1 in every 3rd month." (see https://crontab.guru)
    - cron: '0 0 1 */3 *'
jobs:
  build:
    name: Cleanup Snapshot Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.GHA_REF }}
          fetch-depth: 0
          token: ${{ secrets.GIT_USER_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18.11.0

      - name: Cleanup Snapshot Artifacts
        uses: collaborationFactory/github-actions/.github/actions/artifacts@master
        env:
          JFROG_BASE64_TOKEN: ${{ secrets.JFROG_BASE64_TOKEN }}
          JFROG_URL: ${{ secrets.JFROG_URL }}
          JFROG_USER: ${{ secrets.JFROG_USER }}
          ONLY_BUMP_VERSION: true
          BASE: ${{ inputs.GHA_BASE }}


  tag:
    needs: [build, e2e-tests]
    uses: collaborationFactory/github-actions/.github/workflows/fe-tag.yml@master
    with:
      GHA_REF: ''
      GHA_BASE: ${{ github.event.before }}
    secrets:
      JFROG_BASE64_TOKEN: ${{ secrets.JFROG_BASE64_TOKEN }}
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_USER: ${{ secrets.JFROG_USER }}
      GIT_USER_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
      GIT_USER: ${{ secrets.GIT_USER }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
