name: Check wether upmerge is necessary on a CRON Schedule

on:
  workflow_call:
    secrets:
      SLACK_TOKEN_UPMERGE:
        required: true
      GIT_USER_EMAIL:
        required: true
      GIT_USER:
        required: true
        
jobs:
  check-upmerge:
    name: Run Upmerge Flow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.GHA_REF }}
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.2

      - name: Cache Node Modules
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: check if upmerge is necessary and post to slack
        uses: collaborationFactory/github-actions/.github/actions/upmerge@master
        env:
          SLACK_TOKEN_UPMERGE: ${{ secrets.SLACK_TOKEN_UPMERGE }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER: ${{ secrets.GIT_USER }}
          
