name: Frontend E2E Workflow

on:
  workflow_call:
    secrets:
      PERCY_TOKEN:
        required: false
    inputs:
      GHA_REF:
        type: string
        required: true
      GHA_BASE:
        type: string
        required: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        target: ['e2e']
        jobIndex: [1, 2, 3, 4]
    env:
      jobCount: 4

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.GHA_REF }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18.18.2

      - name: Cache Node Modules
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install modules
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Cypress
        run: |
          echo "Current Cypress cache:"
          npx cypress cache path
          npx cypress cache list
          echo "Clearing Cypress cache..."
          npx cypress cache clear
          npx cypress verify

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Affected Regression Tests
        uses: collaborationFactory/github-actions/.github/actions/run-many@master
        with:
          target: ${{ matrix.target }}
          jobIndex: ${{ matrix.jobIndex }}
          jobCount: ${{ env.jobCount }}
          base: ${{ inputs.GHA_BASE }}
          ref: ${{ inputs.GHA_REF }}
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_PARTIAL_BUILD: 1
          DEV_STORIES: true
          NODE_OPTIONS: --max-old-space-size=4096
          DEBUG: cypress:*
          TZ: 'UTC'
          CYPRESS_FORCE_TIMEZONE: 'UTC'  # Force Cypress to use UTC
          CYPRESS_RETRIES: 2  # Add retries for flaky time-related failures

      - name: Upload E2E Videos
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.target }}-${{ matrix.jobIndex }}-e2e-videos
          path: |
            dist/cypress/apps/**/videos/
          retention-days: 3

      - name: Upload A11Y Reports
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.target }}-${{ matrix.jobIndex }}-a11y-reports
          path: |
            dist/cypress/apps/**/a11y/html/
          retention-days: 3
