name: Frontend E2E Workflow

on:
  workflow_call:
    secrets:
      PERCY_TOKEN:
        required: false
    inputs:
      GHA_REF:
        type: string
        required: true
      GHA_BASE:
        type: string
        required: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.15.0
      options: --user 1001
    timeout-minutes: 120
    strategy:
      matrix:
        target: ['e2e']
        jobIndex: [1, 2, 3, 4]
    env:
      jobCount: 4
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ inputs.GHA_REF }}
          fetch-depth: 0

      - name: Cache Node Modules
        id: npm-cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Cypress Binary
        run: npx cypress install

      - name: Fetch base branch
        run: git fetch origin ${{ inputs.GHA_BASE }}:${{ inputs.GHA_BASE }} || true

      - name: Affected Regression Tests
        id: regressionTests
        continue-on-error: true
        uses: collaborationFactory/github-actions/.github/actions/run-many@master
        with:
          target: ${{ matrix.target }}
          jobIndex: ${{ matrix.jobIndex }}
          jobCount: ${{ env.jobCount }}
          base: ${{ inputs.GHA_BASE }}
          ref: ${{ inputs.GHA_REF }}
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_PARTIAL_BUILD: 1
          DEV_STORIES: true
          CYPRESS_INTERNAL_BROWSER_CONNECT_TIMEOUT: 300000
          NODE_OPTIONS: --max-old-space-size=4096
          CYPRESS_NO_COMMAND_LOG: 1

      - name: Upload E2E Videos
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist-${{ matrix.target }}-${{ matrix.jobIndex }}-e2e-videos
          path: |
            dist/cypress/apps/**/videos/
          retention-days: 3

      - name: Upload A11Y Reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist-${{ matrix.target }}-${{ matrix.jobIndex }}-a11y-reports
          path: |
            dist/cypress/apps/**/a11y/html/
          retention-days: 3

      - name: Fail pipeline if regressionTests step failed
        run: |
          if [ "${{ steps.regressionTests.outcome }}" = "failure" ]; then
            echo "Regression tests step failed, failing the pipeline."
            exit 1
          fi
