name: Frontend Install Dependencies Workflow

on:
  workflow_call:
    inputs:
      GHA_REF:
        type: string
        required: true
    secrets:
      DOT_NPMRC:
        required: true

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.GHA_REF }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14.16.1
      - name: Cache Node Modules
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Use .npmrc
        uses: bduff9/use-npmrc@v1.1
        with:
          dot-npmrc: ${{ secrets.DOT_NPMRC }}

      - name: Install modules
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
