name: Frontend Pull Request Close Workflow

on:
  workflow_call:
    inputs:
      GHA_BASE:
        type: string
        required: true
    secrets:
      JFROG_BASE64_TOKEN:
        required: true
      JFROG_URL:
        required: true
      JFROG_USER:
        required: true
      DOT_NPMRC:
        required: true

jobs:
  remove-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
      - name: Cache Node Modules
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Use .npmrc
        uses: bduff9/use-npmrc@v1.1
        with:
          dot-npmrc: ${{ secrets.DOT_NPMRC }}

      - name: Install modules
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Delete Snapshots from NPM Registry
        uses: collaborationFactory/github-actions/.github/actions/artifacts@feature/PFM-ISSUE-26057-Allow-private-registry-in-Github-Actions-
        env:
          JFROG_BASE64_TOKEN: ${{ secrets.JFROG_BASE64_TOKEN }}
          JFROG_URL: ${{ secrets.JFROG_URL }}
          JFROG_USER: ${{ secrets.JFROG_USER }}
          ONLY_DELETE_ARTIFACTS: true
          BASE: ${{ inputs.GHA_BASE }}
          PR_NUMBER: ${{ github.event.number }}
