name: Frontend Visual Regression Testing Workflow

on:
  workflow_call:
    secrets:
      PERCY_TOKEN:
        required: false
    inputs:
      GHA_REF:
        type: string
        required: true
      GHA_BASE:
        type: string
        required: true

jobs:
  vrt:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.19.1
      - name: Cache Node Modules
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Use .npmrc
        uses: bduff9/use-npmrc@v1.1
        with:
          dot-npmrc: ${{ secrets.DOT_NPMRC }}

      - name: Install modules
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install chrome
        run: npx puppeteer browsers install chrome

      - name: Helles UI Visual Regression Testing
        run: npx nx run helles-ui:vrt
        env:
          WAIT_ON_TIMEOUT: 600000

      - name: Upload VRT Reports
        uses: actions/upload-artifact@v4
        with:
          name: dist-ubuntu-vrt-reports
          path: |
            libs/helles-ui/backstop_data/ci_report/
            libs/helles-ui/backstop_data/html_report/
          retention-days: 3
