name: 'Pull Request'
on:
  pull_request:
    branches:
      - '**'

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Cache Node Modules
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install modules
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Jest Tests
        run: npm test
